# Generated by Django 3.0 on 2022-07-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_faculty_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='rollid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='rollid1',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
